### ISSUE TITLE
Play button not visible

### ISSUE THREAD

**Issue by tursics** [wdr-data/code4maus#23]
### Expected Behavior

The play button and other important elements of the page should be visible.

### Actual Behavior

It's possible to zoom in the page. If I zoom the page, the play button and other elements of the page are partly or complete invisible.

### Steps to Reproduce

You can pinch to zoom in the code area. So the code blocks are zoomed in and out. That's fine. But it's possible to pinch outside the code area and the complete website is zoomed. That's odd.

### Operating System and Browser

Windows with IE
(you can also try it with Chrome or FireFox and zoom in with Ctrl-+)
![Bildschirmfoto 2019-03-29 um 08 42 45](https://user-images.githubusercontent.com/5406352/55217420-c7140880-51ff-11e9-93d5-e4eac82c2049.png)
![Bildschirmfoto 2019-03-29 um 08 45 15](https://user-images.githubusercontent.com/5406352/55217421-c7140880-51ff-11e9-9718-5a4c192b9d20.png)

**Comment by realansgar** [comment]
The [StageHeader component](https://github.com/wdr-data/code4maus/blob/develop/src/components/stage-header/stage-header.jsx) contains the [control buttons](https://github.com/wdr-data/code4maus/blob/develop/src/components/controls/controls.jsx), the three menu buttons and copyright information. This component [gets a fixed width](https://github.com/wdr-data/code4maus/blob/develop/src/components/stage-header/stage-header.jsx#L31) that is calculated [here](https://github.com/wdr-data/code4maus/blob/develop/src/lib/screen-utils.js) at every screen resize.
This stage size is otherwise used for the Scratch stage. The intention here probably was to display the stage and all buttons above it at the same width. This already doesn't happen since all buttons have a fixed width themselves.
Proposed fix: remove this fixed width and change the [margin-right  property](https://github.com/wdr-data/code4maus/blob/develop/src/components/stage-header/stage-header.css#L34) to add a new fixed margin between the control buttons and the three menu buttons.

**Comment by P3nny** [comment]
User-Post 01.04.2020: Der Playbutton ist leider nur halb zu sehen. Aber er funktioniert. Ich benutze Firefox auf Mac Sierra.
